Hi there! My name is Berry. Glad to see another face that's not undead. Our village has been under constant pressure by some unknown evil... 

If you're looking to help us out, I can sell you weapons and armor for a discount.